print ("================================================\n AKIBA STUDENT PROFILE\n================================================")
fullName=input("Enter your Full Name:")
Age =int(input("Enter your Age:"))
Department=input("Enter Departmennt:")
Student_ID= input("Enter student  ID:")
City=input("Enter city:")
University=input("Enter University:")
Email=input("Enter @Email:")
phone_number=int(input("Enter phone number:"))
Favoritelanguage=input("Enetr favourite programming language:")
goal=input("Enter programming Goal:")

print ("================================================\n AKIBA STUDENT PROFILE\n================================================")
print (f"Name:  {fullName}\n StudentID: {Student_ID}\n Age:  {Age}\n city:   {City}\n University:  {University}\n Department:  {Department}\n Email:  {Email}\n Phonenumber:  {phone_number}\n favourite Language:  {Favoritelanguage}\n programming Goal:\n  {goal}\n\n ================================================")