print( "Akiba studentt card ")
student_name= (input("Enter your full name:"))
Student_ID = (input("Enter Your  Id :"))
Department= input("Enter your department:")
year=  int(input("Enter your year:"))
University = input("Enter your university:")
phone_number=  int(input("Enter your Phone number:"))
print( "Akiba student card:")
print(f" Name:{student_name}\n ID:{Student_ID}\n Department:{Department}\n Year:{year}\n University:{University}\n Phone:{phone_number}")