print("========================================")
print("        STUDENT INTRODUCTION")
print("========================================")

full_name = input("Enter your full name: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
university = input("Enter your university: ")
department = input("Enter your department: ")
favorite_language = input("Enter your favorite programming language: ")
programming_goal = input("Enter one programming goal: ")

print("\n========================================")
print("        STUDENT INTRODUCTION")
print("========================================")

print(f"\nMy name is {full_name}.")
print(f"I am {age} years old.")
print(f"I live in {city}.")
print(f"I study at {university}.")
print(f"My department is {department}.")
print(f"My favorite programming language is {favorite_language}.")
print(f"My programming goal is to {programming_goal}.")